name: Greetings

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: Suvraneel/Greeting-action@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        issue_message: 'Hello @${{github.actor}}, thanks for creating your first issue at npmBox, hope you followed the guidelines.'
        pr-message: 'Congratulations!! for making your first PR at  npmBox, our mentors will review it soon.'
